fix: Add missing `formGroupName` for nested controls
Fixes:
    product-list.component.ts:49 ERROR
    Error: Cannot find control with name: 'image'
    Error: Cannot find control with name: 'description'
    Error: Cannot find control with name: 'category'